# Generated by Django 5.2.8 on 2026-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("system_prompt", models.TextField(verbose_name="Системный промпт")),
            ],
            options={
                "verbose_name": "Аватар",
                "verbose_name_plural": "Аватары",
                "ordering": ["id"],
            },
        ),
    ]
