# Generated by Django 5.2.8 on 2026-03-14 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avatar",
            options={"ordering": ("id",), "verbose_name": "Аватар", "verbose_name_plural": "Аватары"},
        ),
    ]
