# Generated by Django 5.2.8 on 2026-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avatars", "0002_alter_avatar_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
    ]
