# Generated by Django 5.2.8 on 2026-03-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avatars", "0002_alter_avatar_options"),
        ("memory", "0001_initial"),
        ("users", "0002_alter_user_options_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("text", models.TextField(verbose_name="Факт")),
                (
                    "avatar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="avatars.avatar",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт долгосрочной памяти",
                "verbose_name_plural": "Факты долгосрочной памяти",
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="AvatarFact",
        ),
        migrations.AddIndex(
            model_name="memoryfact",
            index=models.Index(fields=["user", "avatar"], name="memory_memo_user_id_ef890e_idx"),
        ),
    ]
