# Generated by Django 5.2.8 on 2026-03-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "active_avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_users",
                        to="avatars.avatar",
                        verbose_name="Текущий аватар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь системы",
                "verbose_name_plural": "Пользователи системы",
                "ordering": ["id"],
            },
        ),
    ]
