# Generated by Django 5.2.8 on 2026-03-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("telegram_id", models.BigIntegerField(unique=True, verbose_name="Telegram ID")),
                ("first_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Имя")),
                ("last_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Фамилия")),
                ("language_code", models.CharField(blank=True, max_length=20, null=True, verbose_name="Код языка")),
                ("is_premium", models.BooleanField(default=False, verbose_name="Премиум")),
                ("photo_url", models.TextField(blank=True, null=True, verbose_name="URL фото")),
                (
                    "added_to_attachment_menu",
                    models.BooleanField(default=False, verbose_name="Добавлен в attachment menu"),
                ),
                ("allow_write_to_pm", models.BooleanField(default=True, verbose_name="Разрешена запись в PM")),
                (
                    "last_auth_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата последней авторизации"),
                ),
                (
                    "last_query_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Последний query id"),
                ),
                (
                    "last_start_param",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Последний start param"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to="users.user",
                        verbose_name="Пользователь системы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль Telegram пользователя",
                "verbose_name_plural": "Профили Telegram пользователей",
                "ordering": ["id"],
            },
        ),
    ]
