# Generated by Django 5.2.8 on 2026-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramuser",
            options={
                "ordering": ("id",),
                "verbose_name": "Профиль Telegram пользователя",
                "verbose_name_plural": "Профили Telegram пользователей",
            },
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
